### ISSUE TITLE
Issue with <updated> field in Atom fields

### ISSUE THREAD

**Issue by mark-up** [NinjaForge/Ninja-RSS-Syndicator#3]
The latest release of the J2.5 version contains a major bug introduced by me. Prior to my patch, the <updated> field always used the 'created' date, regardless of whether there were later updates to the article.

I changed this to use the 'modified' date. 

However, by default, the modified date is 1970. This is used if there are no updates to the article, and breaks feeds.

Suggested fix is to compare the 'created' and 'modified' dates and use the most recent one for the <updated> field.

**Comment by omar84** [comment]
can you please give steps as to how to replicate the issue?

**Comment by mark-up** [comment]
Hi Omar,

Replication isn't necessary, since I am describing what needs to be changed.

See lines 1181 to 1184 in com_ninjarsssyndicator/views/ninjarsssyndicator/tmpl/feedcreator.class.php

```
$itemDate = new FeedDate($this->items[$i]->date);
$itemUpdated = new FeedDate($this->items[$i]->updated);
$feed.= "<published>".htmlspecialchars($itemDate->iso8601())."</published>\n";
$feed.= "<updated>".htmlspecialchars($itemUpdated->iso8601())."</updated>\n";
```

What we need is for the 'updated' date to _always_ be >= (greater than or equal to) the 'published' date.

The published date is the Joomla article 'created' date.  
The updated date is the Joomla article 'modified' date.

If the Joomla article is never edited after publishing, Joomla uses its default date (some date in the 1970's). This is a problem because as I mentioned earlier, the 'updated' date must _always_ be greater than or equal to the 'published' date.

Something like this should work (pseudo code):

```
$itemDate = new FeedDate($this->items[$i]->date);
$itemUpdated = new FeedDate($this->items[$i]->updated);
if $itemDate > $itemUpdated {
    $itemUpdated = $itemDate;
}
$feed.= "<published>".htmlspecialchars($itemDate->iso8601())."</published>\n";
$feed.= "<updated>".htmlspecialchars($itemUpdated->iso8601())."</updated>\n";
```

**Comment by mark-up** [comment]
Hi Omar,

To replicate:
1. Install a new instance of J3.0, using the blog sample content.  
2. Install the latest NRSS for J3.0  
3. Set up a feed using all default settings, but set feed type to Atom.  

When you view your feed, one of them will have this entry:  

```
<entry>
    <title>About</title>
    <link rel="alternate" type="text/html" href="http://ninjaforge.com/demo/j30/index.php/about"/>
    <published>2011-01-01T00:00:01+00:00</published>
    <updated>1970-01-01T00:00:00+00:00</updated>
    <id>http://ninjaforge.com/demo/j30/index.php/about</id>
    <author>
        <name>Joomla</name>
        <email>mark@ninjaforge.com</email>
    </author>
    <content type="html"><![CDATA[<p>This tells you a bit about this blog and the person who writes it. </p><p>When you are logged in you will be able to edit this page by clicking on the edit icon.</p>]]></content>
    <summary type="html"><![CDATA[<p>This tells you a bit about this blog and the person who writes it. </p><p>When you are logged in you will be able to edit this page by clicking on the edit icon.</p>]]></summary>
</entry>
```

Note the _published_ and _updated_ fields.

**Comment by omar84** [comment]
fixed in both 2.5 and 3.0 and uploaded to the repo, please confirm and then publish

**Comment by mark-up** [comment]
Confirmed working. Thanks :)

**Comment by mark-up** [comment]
Hi Omar,

This issue apparently still exists. See: http://ninjaforge.com/forum/topic/26186-how-translate-the-qread-moreq-in-the-rss-feed#p32909

**Comment by omar84** [comment]
Hi Mark,

the link provided is one that is about the language file and not the bug in question.

**Comment by omar84** [comment]
issue fixed for J2.5 and J3.0, updated repo.

for the record, it is not the same issue, it is a similar issue in a different feed type (RSS2) this time instead of ATOM.

please confirm and re-release.
